### PR TITLE
#74 Improve failure reporting

### PR DESCRIPTION
**Pull request by tomisaacson**
Change instance tag rule to function so we can use print().
Return instance map from get_aws_instances so we know the name.
Add failure description.

### CODE REVIEW

**Comment by tomisaacson** [comment]
This now prints:

- The name of the failing aws_instance.
- The list of tags missing.

**Comment by tomisaacson** [comment]
I didn't realise this would pick up my other commit for #83, I can split this out if necessary.

**Comment by rberlind** [comment]
Hi @tomisaacson.  I feel your changes here make the policy quite a bit more complicated.

Your change in the get_aws_instances() function seems unnecessary. A module could have more than one aws_instance resource, so using aws_instance instead of instances is not ideal.

I also feel you're breaking the Sentinel convention of having the main rule refer to other rules by recasting the original instance_tags rule as a function.  I see why you're doing it (so you can do more complicated processing), but it seems overly complicated.

Also, I want to mention that you actually can use the print() function inside rules since it always returns true; you just need to add a logical operator between the print() and the other conditions.  If you use it before a condition with the "and" operator, you will see all instances printed up to and including the first one that failed. If you use it after the condition with the "or" operator, you will see the first one that fails only.  The reason is that Sentinel does short-circuit logic which means it stops evaluating expressions within compound boolean conditions once it determines that it knows the final outcome. So, if it evaluates "A and B" and A is false, it won't evaluate B.  If it evaluates "A or B" and A is true, it won't evaluate B.

While my approach will not print the missing tags, looking at the plan would show that.

**Comment by tomisaacson** [comment]
With respect to get_aws_instances() I'm not sure what you mean. I'm still handling multiple aws_instance resources (I've tested this), I'm just capturing the whole thing rather than just the value so I can get the name and report it later.

I don't know anything about Sentinel conventions (there's nothing in the documentation), I'm just trying to achieve better failure reporting. Frankly I found the original implementation kind of useless because it returned so little information. If there's a better way of achieving this then I'm happy to hear it.

I tried using print() inside the rule and it didn't work so I raised a question with Hashicorp (https://support.hashicorp.com/hc/en-us/requests/12155) and they said it wasn't possible. You might want to let your support people know.

You can reduce the complexity and require devs to look at the plan but I think this is a bit old-fashioned. My ideal would be an extension for VSCode (for example) that was able to underline the errors and give hints as to what is missing. This idea of "it's wrong but I'm not going to tell you why" isn't constructive - just look at the way Rust reports errors to see the way modern languages are evolving.

If you genuinely think these improvements are bad then I can resubmit as a separate rule, but I think there's value in this approach that others will benefit from.

**Comment by rberlind** [comment]
Thanks for clarifying the reasons for your change, @tomisaacson .  To be honest, I had overlooked the fact that you had removed the values() function from the get_aws_instances() function and had been focusing on your change of instances to aws_instance in that function.  That was the change that I thought unnecessary and misleading since each evaluation of `tfplan.module(path).resources.aws_instance` could contain multiple instances. I apologize for not having realized the more substantial change you had made in that function.

You do raise a good point that the original policy and many like it do not actually flag the actual EC2 instance or instances that violated the policy.  This and many others in the repository were written at a time when I and other SEs here at HashiCorp did not yet realize that we could use the print() function inside rules. 

A project I have planned to implement in the near future is to add print() functions to all of the example policies and to make sure that they all start out by looking or the particular resource they are focused on in all modules.  I'll update this policy first and do a PR to add it.  I will then let you know.  Hopefully, it will then meet your needs.

I'll try out your rule and re-consider your PR.

For now, what you could do is use the following rule:
```
# Instance tag rule
instance_tags = rule {
    all aws_instances as _, instances {
    	all instances as index, r {
            all mandatory_tags as t {
                (r.applied.tags contains t) or print("tags of violating instance:", r.applied.tags)
            }
        }
    }
}
```

If you include a name or Name tag with the name of the instance, I think this should give you what you are looking for since the name tag would presumably help you find the actual occurrence of the aws_instance resource in your Terraform code that was missing the mandatory tag.

Thanks
Roger Berlind

**Comment by rberlind** [comment]
Hi @tomisaacson:  As part of a broader project to introduce reusable Sentinel functions that can be used across Sentinel policies (although initially only by pasting them into each policy), I plan on doing a PR which will include this version of the policy:

```
import "tfplan"

# Get all instances of specific resource in plan from all modules
find_resources_from_plan_with_names = func(r) {
  resources = []
  for tfplan.module_paths as path {
    # Append the entire resources map, not just the values
    # so that we have the names of the resources.
    # In case the module does not have any resources of the
    # specified, we append the empty map, {}.
    append(resources, (tfplan.module(path).resources[r] else {}))
  }
  return resources
}
  
mandatory_tags = [
  "TTL", 
  "Owner",
]
  
# General function to validate that all instances of resources have an attribute
# within a provided list of allowed values.
validate_resource_attribute_contains_list = func(resource_type, attribute, required_values) {
  # resource_type is the type of resource such as "aws_instance"
  # attribute should be a string naming a single attribute of a resource
  # This attribute should be a map or a list such as tags in AWS resources
  # required_values is the list of required values for the attribute
  # We first extract the maps from the main list
  list_of_resource_maps = find_resources_from_plan_with_names(resource_type)
  for list_of_resource_maps as resource_map {
    # for each map, we get the name and map of resources
    for resource_map as name, resources {
      # We then get each instance and test it
      for resources as _, r {
        for required_values as rv {
          if r.applied[attribute] not contains rv {
            print("first violator:", name,
              ", attribute missing required values:", attribute,
              ",  first missing value:", rv)
            return false
          }
        }
      }
    }
  }
  print("No violators")
  return true
}

# Rule to restrict instance types allowed
check_mandatory_tags = rule {
  validate_resource_attribute_contains_list("aws_instance", "tags", mandatory_tags) is true
}
  
# Main rule that requires other rules to be true
main = rule {
  (check_mandatory_tags) else true
}
```
The output for a violation of the policy would look like this:

`first violator: ubuntu , attribute missing required values: tags , first missing value: ttl`

Note that the second function is intentionally somewhat abstract and does not refer to tags at all. That means that the outputs from the print() function are a bit generalized.  But I believe having functions like this will make it easier for people to create new policies since they can then focus on just passing in desired arguments to them when calling in their rules.

Please take a look and let me know what you think.  Even better, try using this policy.

Thanks
Roger

**Comment by rberlind** [comment]
I want to note @tomisaacson  that if and when we have reusable Sentinel function in TFE, the above policy would look like this since it would not have to include the function definitions:

```
# Rule to restrict instance types allowed
check_mandatory_tags = rule {
  validate_resource_attribute_contains_list("aws_instance", "tags", mandatory_tags) is true
}
  
# Main rule that requires other rules to be true
main = rule {
  (check_mandatory_tags) else true
}
```

**Comment by rberlind** [comment]
Hi @tomisaacson,

I recently added some second-generation policies under https://github.com/hashicorp/terraform-guides/tree/master/governance/second-generation that now do a much better job of reporting all violations that the Terraform code being checked generate including the full addresses of the resources that cause the violations including module paths.  So, they now print messages like "EC2 instance module.nested.module.nested-again.aws_instance.ubuntu-three[0] has instance_type t2.micro that is not in the allowed list: ["t2.small" "t2.medium" "t2.large"]".

I think you will find the new policies much more useful than the old ones.

It took much longer than I had intended to get those policies created.  I wanted to thank you again for this PR which lead me to re-evaluate the outputs that were being generated by the Sentinel policies and how to make them much better.

I'm going to close this PR since I think the new https://github.com/hashicorp/terraform-guides/blob/master/governance/second-generation/aws/enforce-mandatory-tags.sentinel policy does what you had asked for and more.

Roger

**Pull request closed without merging**
