### PR TITLE
pTFE Packer OVF

### PR DESCRIPTION
**Pull request by jboero**
A basic Packer file for CentOS with Replicated installed and ready to bootstrap.  For use with nonprod demonstrations or travelling VirtualBox demos.

### CODE REVIEW

**Comment by rberlind** [comment]
Hi @jboero .  I think you accidentally included local changes to infrastructure-as-code/aws-ec2-instance/variables.tf which don't seem to belong in this PR.  Could you back those out?  If needed, create a new branch from master and then add your packer PTFE OVF.

**Comment by rberlind** [comment]
Hi again, @jboero .  I tried running `packer build ptfe-packer.json` but got error 

==> virtualbox-iso: Retrieving ISO
    virtualbox-iso: Error downloading: Error making HTTP GET request: 404 Not Found
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

Also, `curl https://mirror.umd.edu/centos/7/isos/x86_64/CentOS-7-x86_64-Everything-1804.iso` gives 404.  That is because the version has changed from 1804 to 1810.  The checksum also is different now.

So, you need the following:

```
      "iso_url": "https://mirror.umd.edu/centos/7/isos/x86_64/CentOS-7-x86_64-Everything-1810.iso",
      "iso_checksum": "918975cdf947e858c9a0c77d6b90a9a56d9977f3a4496a56437f46f46200cf71",
```

If you can figure out a way to make Packer inspect the directory, determine the current version and checksum, and then use those, that would be good.  Otherwise, you should add instructions suggesting that the reader do this and update the json file if needed.

I'm currently running packer and it seems to be working.

It would also be good to include instructions on using Packer to build the image.  Of course, that is `packer build ptfe-packer.json`.

I think you should also give full instructions for creating a new Virtual Box VM from the image and configuring the network for it.  I'm not exactly sure what to do for that.

Also, will /etc/sysconfig/replicated be inside the VM?

There is a typo in your README.md: "upate" should be "update".

**Comment by rberlind** [comment]
My packer build did finish successfully.
I was also able to import the vmdk file into Virtual Box.
I was also able to start the VM.

I'm still not sure what IP address you are suggesting we update in /etc/sysconfig/replicated.

What Virtual Box networking mode do you recommend? NAT with port forwarding on ports 8800, 443, and 80?

What should I use as hostname in the admin console? The private IP address?

**Comment by rberlind** [comment]
I used the private IP and was then able to use self-signed certs, upload license, save other settings in demo mode, and start the app. But I could not bring up app on the private IP.  I suspect I should have used localhost.

**Comment by jboero** [comment]
Thanks Roger your feedback is detailed and appreciated as always.  You're right the PR seems a lil sloppy right now.  I'll resubmit a cleaner one with updated ISO.  It looks like we also specified a subpar mirror too.  I generally download or use a local ISO locally with packer.  Stay tuned.

**Pull request closed without merging**
