### PR TITLE
Two new policies restricting SSH and RDP for 0.0.0.0/0 for AWS SGs

### PR DESCRIPTION
**Pull request by ja5onhughe5**
Created new 3rd Gen policies for restricting SSH and RDP. They have similar targeting as terraform-foundational-policies-library/cis/aws/networking/aws-cis-4.2-networking-deny-public-rdp-acl-rules and terraform-foundational-policies-library/cis/aws/networking/aws-cis-4.1-networking-deny-public-ssh-acl-rules but adds "read" and "no-op" to resource changes, loops through both the aws_security_group and the aws_security_group_rule resources, and provides greater detail of violations.

Two new policy sets were added:
restrict-ingress-sg-rule-rdp
restrict-ingress-sg-rule-ssh

Changes were made to:
tfplan-function - adding "filter_attribute_less_than_equal_to_value" and "filter_attribute_greater_than_equal_to_value".

### CODE REVIEW

**Comment by rberlind** [comment]
Thanks @ja5onhughe5 : I'll review later today or tomorrow.

**Review by rberlind — COMMENTED** [review]
@ja5onhughe5 : Did you explicitly make changes to the tfplan-functions.sentinel module?  Or is it possible you had forked the repository before I made changes to add in the extra part of the violation message that prints what the value is supposed to be when it is null or undefined?

In any case, I would want to keep the extra message part that the master branch has.

**Review by rberlind — COMMENTED** [review]
Also, do you really need a filter_attribute_greater_than_equal_to_value() function when we already have filter_attribute_greater_than_value() given that you are passing an integer to it?  Couldn't you just pass an integer to the other function that is the value minus 1?

**Comment by ja5onhughe5** [comment]
I made changes directly to the tfplan-functions.sentinel module in adding the filter_attribute_greater_than_equal_to_value() and filter_attribute_less_than_equal_to_value() functions, but had removed the extra portion of the violation message for the two new functions. Removing it was based on my own personal opinion of not needing it, but definitely not a set opinion if it makes sense in other applications.

As far as the need for the filter_attribute_greater_than_equal_to_value() function, setting the value as minus 1, I believe, would work. However, when providing/passing variables for a specific integer, being associated to a service/port (in reference to the to_port/from_port in SGs) or any other relationship it may have, it makes sense, specifically to me, for the filter_attribute_greater_than_equal_to_value() to exist.

**Review by rberlind — COMMENTED** [review]
@ja5onhughe5 : I'm ok with adding the two new functions, but please do restore the extra portions of the messages like `+ "It is supposed to be less" + "than or equal to " + to_string(value)`  and `+ "It is supposed to be greater " + "than or equal to " + to_string(value)` from where you removed them and please also add similar messages to your two new functions.

My view is that it is very important in Sentinel policies to always tell the person who violated them what the actual allowed values are so that they can fix their Terraform code to make it compliant with the policies it violated without having to ask someone on the governance team (if there is one) what the allowed values are.

Note that the messages are the opposite of the names of the functions since the functions look for violations.  so your text for the filter_attribute_greater_than_equal_to_value() function would be `"It is supposed to be less than" + to_string(value)` and your text for your filter_attribute_less_than_equal_to_value() function would be `"It is supposed to be greater than" + to_string(value)`.

**Comment by ja5onhughe5** [comment]
I will add the messages back, and I also just wrote messages for null values in the aws_security_group_rules loop that I will put in an additional pull request for.

I am very grateful and appreciative to be able to contribute to this work.

**Comment by rberlind** [comment]
I am curious what lead you to submit your PR and how you are using
Sentinel, Jason.
Could you let me know the company you work for and whether they have
licensed Terraform Cloud or Terraform Enterprise?
You can send me an email at roger@hashicorp.com.

Roger Berlind
Global Technology Specialist
HashiCorp

**Comment by ja5onhughe5** [comment]
I would be more than happy to send an email. I will get it out to you tomorrow afternoon.

**Comment by rberlind** [comment]
Thanks!
Roger

**Review by rberlind — APPROVED** [review]
Thanks for doing the extra work to update the policies, @ja5onhughe5 .
These are both good. I cloned your repo and tested them with `sentinel test -verbose` to validate that they work as desired and that they print useful violation warnings.

I did edit your tfplan-functions.sentinel in your master branch to put in the extra messages saying what the value is supposed to be in case it is null.

**Pull request merged**
