### PR TITLE
added terraform-0.12-examples

### PR DESCRIPTION
**Pull request by rberlind**
Added my Terraform 0.12 examples that we used during Q4 SE training.  These had been in my own personal repository.

### CODE REVIEW

**Comment by ncorrare** [comment]
I wasn't able to test the jsondecode examples, every other example run perfect!. I do have concerns over hardcoding AMI-IDs in case they chance, but other than that, 👍 LGTM

**Comment by rberlind** [comment]
Thanks @ncorrare .  I added aws_ami data sources to fetch AMI.  I also removed availability zone from subnets which was not needed.  Doing that now allows the examples to be run in any AWS region.  Users can change the region being passed to the AWS provider in examples that use it.

Could you look at the changes and then submit an approving review so that I can merge?  Thanks.

**Comment by rberlind** [comment]
Note that I did test all the modified code.

**Comment by rberlind** [comment]
I tested all examples with Terraform 0.12 alpha-4 and updated README.md accordingly to refer to alpha-4.

**Comment by Arslan-SE** [comment]
We've tested these at training. Roger made updates to reflect alpha 4 and has retested.

**Pull request merged**
